"""Add Subscriber model

Revision ID: d0bfb81a6a61
Revises: 3e9e66202427
Create Date: 2024-12-03 12:10:17.905061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0bfb81a6a61'
down_revision = '3e9e66202427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('table_number',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('table_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
